version: '3.8'

networks:
  test-network:
    name: nexus_test-network

services:
  # Тестовая база данных PostgreSQL
  postgres-test:
    image: postgres:15-alpine
    container_name: nexus-test-postgres
    environment:
      POSTGRES_DB: nexus_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d nexus_test" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    # Более простые настройки для стабильности
    command: >
      postgres -c listen_addresses='*' -c shared_buffers=128MB -c max_connections=100 -c log_connections=on -c log_disconnections=on -c log_statement=all -c wal_level=minimal -c max_wal_senders=0 -c archive_mode=off -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    restart: unless-stopped
    networks:
      - test-network

volumes:
  postgres_test_data:
