/**
 * Константы для инъекции зависимостей в NestJS
 * Используются как токены для Provider.provide
 */

// Character модуль
export const CHARACTER_SERVICE = 'CHARACTER_SERVICE';
export const NEEDS_SERVICE = 'NEEDS_SERVICE';
export const MOTIVATION_SERVICE = 'MOTIVATION_SERVICE';
export const ACTION_SERVICE = 'ACTION_SERVICE';
export const EMOTIONAL_STATE_SERVICE = 'EMOTIONAL_STATE_SERVICE';
export const CHARACTER_BEHAVIOR_SERVICE = 'CHARACTER_BEHAVIOR_SERVICE';
export const SPECIALIZATION_SERVICE = 'SPECIALIZATION_SERVICE';
export const CHARACTER_RESPONSE_SERVICE = 'CHARACTER_RESPONSE_SERVICE';
export const MESSAGE_ANALYSIS_SERVICE = 'MESSAGE_ANALYSIS_SERVICE';
export const TECHNIQUE_EXECUTOR_SERVICE = 'TECHNIQUE_EXECUTOR_SERVICE';
export const MANIPULATION_SERVICE = 'MANIPULATION_SERVICE';

// Dialog модуль
export const DIALOG_SERVICE = 'DIALOG_SERVICE';
export const MESSAGE_SERVICE = 'MESSAGE_SERVICE';

// User модуль
export const USER_SERVICE = 'USER_SERVICE';

// Auth модуль
export const AUTH_SERVICE = 'AUTH_SERVICE';

// LLM модуль
export const LLM_SERVICE = 'LLM_SERVICE';
export const LLM_PROVIDER_MANAGER = 'LLM_PROVIDER_MANAGER';
export const OPENAI_PROVIDER = 'OPENAI_PROVIDER';
export const LLAMA_PROVIDER = 'LLAMA_PROVIDER';

// Prompt Template модуль
export const PROMPT_TEMPLATE_SERVICE = 'PROMPT_TEMPLATE_SERVICE';

// Инфраструктурные сервисы
export const CACHE_SERVICE = 'CACHE_SERVICE';
export const LOG_SERVICE = 'LOG_SERVICE';
export const ERROR_HANDLING_SERVICE = 'ERROR_HANDLING_SERVICE';
export const MESSAGE_QUEUE_SERVICE = 'MESSAGE_QUEUE_SERVICE';
export const VALIDATION_SERVICE = 'VALIDATION_SERVICE';
export const MONITORING_SERVICE = 'MONITORING_SERVICE'; 